### ISSUE TITLE
Levenberg-Marquardt optimizer shows unexpected results

### ISSUE THREAD

**Issue by VikramRadhakrishnan** [tensorflow/graphics#111]
Hello,

I have been trying to use the Levenberg-Marquardt optimizer to find the minimum of a quadratic function. Based on my understanding, with a purely convex function, LM should converge to the global minimum irrespective of the initial guess.

This is the function I am trying to minimize:
```
import tensorflow as tf
def test_function(x):
  y = 5.0 * tf.math.square(x) - 9.0 * x - 3.0
  return y
```

This is a function with a global minimum at x=0.9. However, when I run the optimizer as follows:
```
x = tf.Variable(0.0, name="testvar")

minimize_op = optimizer.minimize(test_function, x, 50)

with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  result = sess.run(minimize_op)
```

And this gives me the value of result as (0.0, [-0.28743422]).
However, I ws expecting something closer to (-7.05, [0.9]), which is the true global minimum.

Also, changing the initial value of x to something else, such as 0.9, results in something weird:
result = (24.851248, [0.9])

This doesn't make any sense to me, because when x=0.9, the function should evaluate to -7.05, and not 24.851248.

**Comment by sofienbouaziz** [comment]
In this case what the LM optimizer will be optimizing is tf.square(y). This is because the API provided by tfg takes the residuals. I will update the doc to make this a bit more clear. The function that you are optimizing has two optimas and the LM optimizer finds correctly one of them.

<img width="1467" alt="Screen Shot 2019-10-31 at 10 58 56 AM" src="https://user-images.githubusercontent.com/6638630/67973423-b9779480-fbcd-11e9-81c0-8cc43d726d0e.png">

**Comment by sofienbouaziz** [comment]
To make this a little more clear LM minimizes a sum of square functions and what tfg expects are a list of functions and internally it will take care of squaring and summing these functions.
