### ISSUE TITLE
While pyramid downsampling, i'm getting this error "TypeError: No loop matching the specified signature and casting was found for ufunc true_divide".

### ISSUE THREAD

**Issue by saahiluppal** [tensorflow/graphics#252]
while just testing for something i found that  tfg.image.pyramid.downsample gives me the following error:
TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

here's the colab reference to this.
https://colab.research.google.com/drive/1OUs2LTAIC5xlzc_6SrnoByv22hEnuAis

**Comment by sofienbouaziz** [comment]
Thanks for reporting this issue. Unfortunately it seems that the colab link is not working or I might not have the permission to access it.

**Comment by saahiluppal** [comment]
Here's the gist
https://gist.github.com/saahiluppal/2cf1848574d562c9c54db7c0da4fd9bb

both upsampling and downsampling gives same error

**Comment by sofienbouaziz** [comment]
This is because the image that you are using is in uint8 for the time being you can fix this by casting your image to float, e.g.,
img = tf.cast(tf.image.decode_image(img, channels=3), dtype=tf.float32) / 255.0
I will think what is the best way to fix this, either casting internally to float and casting back to the original dtype or raising an error.

**Comment by saahiluppal** [comment]
That was a silly mistake.
Thanks for guidance.
