### ISSUE TITLE
Support for symbolic keras tensors in utils.shape

### ISSUE THREAD

**Issue by avneesh-sud** [tensorflow/graphics#322]
utils.shape does not work with symbolic (placeholder) tensors created by Keras.Input. Following code snippet throws an exception.

```
import tensorflow as tf
from tensorflow_graphics.util import shape

input = tf.keras.Input(shape=(100, 3), batch_size=1)
data = tf.ones(shape=(1, 100, 100))
shape.compare_dimensions(
    tensors=(input, data),
    tensor_names=("input", "data"),
    axes=(-2, -2))
```

**Comment by rlav440** [comment]
Hey, since this was linked to my issue:

I'm currently running the DGCNN layers via the keras functional API (with placeholder shape information). I'll edit once I have found the raised issues for confirmation, but I'm pretty sure that this issue is fixed in the Github version - but this fix has not yet made it's way to the pypi package.

Actually, just to confirm this, the above example code does not raise any issues on Ubuntu 19.04 with a version of this repo built from source around 2 weeks ago

**Comment by julienvalentin** [comment]
The pip package needs an update for sure, but this is a separate issue as you rightly point out. As it seem fixed in head, is it safe to close?

**Comment by rlav440** [comment]
I'd think so. Cheers!

**Comment by avneesh-sud** [comment]
Thanks rlav440@ and Julien. Yes - I tested on latest code (vs pip) and the issue is resolved.
